#!/usr/bin/env bash
# bash script that displays several items listed

trap highlander SIGTERM

highlander()
{
  echo "I am invincible!!!"
}

while (( 1 ))
do
	echo "To infinity and beyond"
	sleep 2
done
