#!/usr/bin/env bash
# script to install a firewall an open port 22,80 and 443

frwd="*nat\n\t :PREROUTING ACCEPT [0:0]\n\t -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80"
# install
sudo apt install ufw -y
sudo sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw
#disable the firewall
sudo ufw disable

# allow outgoing traffic and deny incomming traffic
sudo ufw default allow outgoing
sudo ufw default deny incoming

# allow the specified ports
sudo ufw allow ssh
sudo ufw allow https
sudo ufw allow http

sed -i"/\*filter/ i$frwd" /etc/ufw/before.rules

#enable the firewall
sudo ufw enable

# check the status
# sudo ufw status numbered
